export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

export const CURRENCY_FETCH_REQUESTED = 'CURRENCY_FETCH_REQUESTED';
export const CURRENCY_FETCH_SUCCESS = 'CURRENCY_FETCH_SUCCESS';
export const CURRENCY_FETCH_FAILURE = 'CURRENCY_FETCH_FAILURE';
