export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const CURRENCY_FETCH_REQUESTED = 'CURRENCY_FETCH_REQUESTED';
export const CURRENCY_FETCH_SUCCESS = 'CURRENCY_FETCH_SUCCESS';
export const CURRENCY_FETCH_FAILURE = 'CURRENCY_FETCH_FAILURE';
